"""Indexing components for the Knowledge Ingestion Pipeline."""

from .crawler import (
    CrawlerService,
    crawl_url,
    compute_content_hash,
    is_valid_url,
    normalize_url,
    is_same_domain,
    extract_links_from_html,
    extract_links_from_markdown,
    extract_title_from_html,
    extract_title_from_markdown,
    CRAWL4AI_AVAILABLE,
    DEFAULT_MAX_CONCURRENT,
    DEFAULT_JS_WAIT_SECONDS,
)
from .crawl_profiles import (
    CrawlProfile,
    CrawlProfileName,
    CRAWL_PROFILES,
    get_crawl_profile,
    get_profile_for_url,
    apply_proxy_override,
)
from .chunker import chunk_document, chunk_sections, count_tokens, estimate_chunks, ChunkData
from .graphiti_ingestion import (
    ingest_document_as_episode,
    EpisodeIngestionResult,
    EPISODE_ENTITY_TYPES,
)
from .contextual import (
    ContextualChunkEnricher,
    DocumentContext,
    EnrichedChunk,
    ContextualUsageStats,
    ContextualCostEstimate,
    AggregatedContextualStats,
    DEFAULT_CONTEXTUAL_PRICING,
    create_contextual_enricher,
)
from .fallback_providers import (
    CrawlResult,
    CrawlProvider,
    ApifyProvider,
    BrightDataProvider,
    FallbackCrawler,
    SimpleCrawlProvider,
    create_fallback_crawler,
)
from .youtube_ingestion import (
    YouTubeIngestionError,
    TranscriptSegment,
    YouTubeTranscriptResult,
    TranscriptChunk,
    YouTubeIngestionResult,
    extract_video_id,
    fetch_transcript,
    chunk_transcript,
    ingest_youtube_video,
)
# Epic 20 - Hierarchical Chunking (Story 20-C3)
from .hierarchical_chunker import (
    HierarchicalChunk,
    HierarchicalChunkResult,
    HierarchicalChunker,
    create_hierarchical_chunker,
    DEFAULT_LEVEL_SIZES,
    DEFAULT_OVERLAP_RATIO,
    DEFAULT_EMBEDDING_LEVEL,
)
# Epic 20 - Enhanced Table/Layout Extraction (Story 20-D1)
from .enhanced_docling import (
    Position,
    ExtractedTable,
    DocumentSection as EnhancedDocumentSection,
    Figure,
    Footnote,
    DocumentLayout,
    TableChunk,
    EnhancedDoclingParser,
    EnhancedDoclingAdapter,
    get_enhanced_docling_adapter,
    DEFAULT_TABLE_EXTRACTION,
    DEFAULT_PRESERVE_LAYOUT,
    DEFAULT_TABLE_AS_MARKDOWN,
)

__all__ = [
    # Crawler (Story 13.3: Crawl4AI migration)
    "CrawlerService",
    "crawl_url",
    "compute_content_hash",
    "is_valid_url",
    "normalize_url",
    "is_same_domain",
    "extract_links_from_html",
    "extract_links_from_markdown",
    "extract_title_from_html",
    "extract_title_from_markdown",
    "CRAWL4AI_AVAILABLE",
    "DEFAULT_MAX_CONCURRENT",
    "DEFAULT_JS_WAIT_SECONDS",
    # Crawl Profiles (Story 13.4: Configuration profiles)
    "CrawlProfile",
    "CrawlProfileName",
    "CRAWL_PROFILES",
    "get_crawl_profile",
    "get_profile_for_url",
    "apply_proxy_override",
    # Chunker
    "chunk_document",
    "chunk_sections",
    "count_tokens",
    "estimate_chunks",
    "ChunkData",
    # Graphiti ingestion
    "ingest_document_as_episode",
    "EpisodeIngestionResult",
    "EPISODE_ENTITY_TYPES",
    # Epic 12: Contextual Retrieval
    "ContextualChunkEnricher",
    "DocumentContext",
    "EnrichedChunk",
    "ContextualUsageStats",
    "ContextualCostEstimate",
    "AggregatedContextualStats",
    "DEFAULT_CONTEXTUAL_PRICING",
    "create_contextual_enricher",
    # Epic 13: Fallback Providers
    "CrawlResult",
    "CrawlProvider",
    "ApifyProvider",
    "BrightDataProvider",
    "FallbackCrawler",
    "SimpleCrawlProvider",
    "create_fallback_crawler",
    # Epic 13: YouTube Transcript Ingestion
    "YouTubeIngestionError",
    "TranscriptSegment",
    "YouTubeTranscriptResult",
    "TranscriptChunk",
    "YouTubeIngestionResult",
    "extract_video_id",
    "fetch_transcript",
    "chunk_transcript",
    "ingest_youtube_video",
    # Epic 20: Hierarchical Chunking (Story 20-C3)
    "HierarchicalChunk",
    "HierarchicalChunkResult",
    "HierarchicalChunker",
    "create_hierarchical_chunker",
    "DEFAULT_LEVEL_SIZES",
    "DEFAULT_OVERLAP_RATIO",
    "DEFAULT_EMBEDDING_LEVEL",
    # Epic 20: Enhanced Table/Layout Extraction (Story 20-D1)
    "Position",
    "ExtractedTable",
    "EnhancedDocumentSection",
    "Figure",
    "Footnote",
    "DocumentLayout",
    "TableChunk",
    "EnhancedDoclingParser",
    "EnhancedDoclingAdapter",
    "get_enhanced_docling_adapter",
    "DEFAULT_TABLE_EXTRACTION",
    "DEFAULT_PRESERVE_LAYOUT",
    "DEFAULT_TABLE_AS_MARKDOWN",
]
